-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local terminal    = "ghostty"
local fileManager = "dolphin"
local menu        = "hyprlauncher"
local browser     = "google-chrome"

-- Application bindings

local mainMod = "SUPER" -- Sets "Windows" key as main modifier


-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + ESCAPE", hl.dsp.exec_cmd("wlogout --protocol layer-shell"))


-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end

-- Universal COPY/PASTE — forward SUPER+C / SUPER+V as Ctrl+Insert / Shift+Insert
-- to the focused window. Insert-based combos are the X11 clipboard shortcuts that
-- work everywhere, *including terminals* (where Ctrl+C is SIGINT, not copy, which
-- is why the earlier Ctrl+C/Ctrl+V forwarding failed in ghostty/kitty). Close
-- window is on SUPER+Q, so SUPER+C is free for copy.
--
-- `window = "activewindow"` (== hyprland.conf `, active`) is REQUIRED: without an
-- explicit target, sendshortcut fires into a stale/unsettled focus and the first
-- paste silently no-ops (you have to press SUPER+V twice). With it, CA::pass
-- re-acquires keyboard focus on the active surface before synthesizing the key.
-- Plain `hl.bind` (not `binde`/`release`) — sendshortcut is a special dispatcher
-- that already re-fires on key release to send the matching key-up; the edge flag
-- only risks double-firing here.
hl.bind(mainMod .. " + C", hl.dsp.send_shortcut({ mods = "CTRL",  key = "INSERT", window = "activewindow" }))
hl.bind(mainMod .. " + V", hl.dsp.send_shortcut({ mods = "SHIFT", key = "INSERT", window = "activewindow" }))

-- Open App launcher
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd("wofi --show drun"))

-- Toggle the swaync notification center.
-- `swaync-client -t` toggles the control-center visibility; `-sw` skips
-- waiting for the daemon to reload so the panel opens instantly. The daemon
-- itself is started from hyprland.lua on `hyprland.start`.
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("swaync-client -t -sw"))


-- hl.bind("SUPER" .. " + " .. "RETURN", hl.dsp.exec_cmd("uwsm app -- $TERMINAL --dir=$(omarchy-cmd-terminal-cwd)"))
hl.bind("SUPER" .. " + " .. "E", hl.dsp.exec_cmd("uwsm app -- nautilus --new-window"))
-- Exit the session via `uwsm stop` so systemd tears down the wayland-session
-- units and cleans up the activation environment. Bypassing this (raw
-- compositor exit / kill) yanks Hyprland from under clients. A wofi --dmenu
-- prompt (in exit-prompt.sh) confirms first: only the "Exit" choice runs
-- `uwsm stop`; Cancel or Esc (empty selection) is a no-op. The shell logic
-- lives in a script rather than inline so the Lua config avoids long-bracket
-- quoting fragility.
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/exit-prompt.sh"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
-- Reload the Hyprland (Lua) config so edits to this directory apply live,
-- without a full session restart. SUPER+R is the launcher above, so SHIFT
-- reuses the same key for the (less frequent) reload.
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("hyprctl reload"))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))    -- dwindle only

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }))
hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.move({ direction = "down" }))

-- Relative resize of the active window with SUPER + Minus/Equal.
-- `hl.dsp.window.resize` is the Lua equivalent of the `resizeactive` dispatcher:
-- `{ x = dx, y = dy, relative = true }` shifts the active window's size by a
-- pixel delta (width = x, height = y), for both floating and tiled windows.
-- `relative = true` is REQUIRED — without it negative deltas (shrink) are
-- rejected. SUPER + Minus/Equal adjusts width; add SHIFT to adjust height.
-- `repeating = true` keeps resizing while the key is held, like the volume keys.
-- (Spawning `hyprctl dispatch resizeactive -20 0` instead does NOT work: hyprctl
-- parses the leading `-20` as a CLI flag and drops it.)
hl.bind(mainMod .. " + Minus",         hl.dsp.window.resize({ x = -20, y = 0,   relative = true }), { repeating = true })
hl.bind(mainMod .. " + Equal",         hl.dsp.window.resize({ x =  20, y = 0,   relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + Minus", hl.dsp.window.resize({ x = 0,   y = -20, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + Equal", hl.dsp.window.resize({ x = 0,   y =  20, relative = true }), { repeating = true })

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging.
-- preserve_split (see looknfeel.lua) keeps the dwindle split orientation
-- stable during resize, so dragging RMB resizes without flipping the layout.
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })



-- Close windows

hl.unbind("SUPER" .. " + " .. "W")

hl.unbind("CTRL + ALT" .. " + " .. "DELETE")

hl.bind("SUPER" .. " + " .. "Q", hl.dsp.window.close())

hl.bind("SUPER" .. " + " .. "W", hl.dsp.send_shortcut({ mods = "CTRL", key= "W", window = "activewindow"}))
