
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
require("monitors")
require("input")
require("bindings")
require("looknfeel")
require("autostart")

hl.config({ autogenerated = false }) -- remove this line to remove the warning

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
hl.on("hyprland.start", function ()
  hl.exec_cmd("nm-applet")
  -- swaybg sets the wallpaper from the dotfiles repo. hl.exec_cmd routes
  -- through Hyprland's exec dispatcher (/bin/sh), so $HOME expands — no
  -- hardcoded username needed. -m fill scales to cover each output
  -- (cropping overflow) without distorting aspect ratio.
  --
  -- WF-11: the bar / notifications / launcher / power surfaces are now
  -- caelestia, brought up by the systemd `caelestia.service` (see
  -- home-manager/modules/caelestia.nix, wired in WF-10) — NOT by a Hyprland
  -- exec-once. The old waybar, swaync, and the waybar-autoreload watcher
  -- that used to share this handler are gone; swaybg stays (it only shared
  -- waybar's launch line). nm-applet and gnome-keyring-daemon below are
  -- independent of the shell and stay. The retired packages/config dirs
  -- are removed in the WF-16 retirement merge, not here.
  hl.exec_cmd("swaybg -i $HOME/nixos-dotfiles/config/wallpaper/lonely-train.jpg -m fill")
  -- Start the GNOME Keyring secrets daemon so credential-aware apps (gh,
  -- browsers) find an org.freedesktop.secrets provider instead of falling
  -- back to `pass` at ~/.password-store. The login keyring is unlocked at
  -- greetd login via pam_gnome_keyring (see nixos/modules/security/keyring.nix).
  hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")




---------------------
---- KEYBINDINGS ----
---------------------

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})
