-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Application bindings

hl.bind("SUPER + ALT" .. " + " .. "RETURN", hl.dsp.exec_cmd("uwsm-app -- xdg-terminal-exec --dir=$(omarchy-cmd-terminal-cwd) tmux new"))
local terminal = "uwsm app -- $TERMINAL"
local browser = "omarchy-launch-browser"
-- hl.bind("SUPER" .. " + " .. "RETURN", hl.dsp.exec_cmd("uwsm app -- $TERMINAL --dir=$(omarchy-cmd-terminal-cwd)"))
hl.bind("SUPER + SHIFT" .. " + " .. "RETURN", hl.dsp.exec_cmd("omarchy-launch-browser"))
hl.bind("SUPER" .. " + " .. "E", hl.dsp.exec_cmd("uwsm app -- nautilus --new-window"))
hl.bind("SUPER" .. " + " .. "B", hl.dsp.exec_cmd("omarchy-launch-browser"))
hl.bind("SUPER + SHIFT + ALT" .. " + " .. "B", hl.dsp.exec_cmd("omarchy-launch-browser --private"))
hl.bind("SUPER + SHIFT" .. " + " .. "N", hl.dsp.exec_cmd("omarchy-launch-editor"))
hl.bind("SUPER + SHIFT" .. " + " .. "T", hl.dsp.exec_cmd("omarchy-launch-tui btop"))
hl.bind("SUPER + SHIFT" .. " + " .. "D", hl.dsp.exec_cmd("omarchy-launch-tui lazydocker"))
hl.bind("SUPER + SHIFT" .. " + " .. "M", hl.dsp.exec_cmd("omarchy-launch-webapp https://mail.google.com"))
hl.bind("SUPER + SHIFT" .. " + " .. "C", hl.dsp.exec_cmd("omarchy-launch-webapp https://calendar.google.com"))


-- Close windows

hl.unbind("SUPER" .. " + " .. "W")

hl.unbind("CTRL + ALT" .. " + " .. "DELETE")

hl.bind("SUPER" .. " + " .. "Q", hl.dsp.window.close())

hl.bind("SUPER" .. " + " .. "W", hl.dsp.send_shortcut({ mods = "CTRL", key= "W", window = "activewindow"}))
