-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Extra env variables

-- env = MY_GLOBAL_ENV,setting

hl.config({
    ecosystem = {
        no_donation_nag = true,
    },
})
