-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        lock_cmd = "omarchy-system-lock",
        -- lock screen and 1password
        before_sleep_cmd = "OMARCHY_LOCK_ONLY=true omarchy-system-lock",
        -- lock before suspend without scheduling display off.
        after_sleep_cmd = "sleep 1 && omarchy-system-wake",
        -- delay for PAM readiness, then turn on display.
        inhibit_sleep = 3,
        -- wait until screen is locked
    },
})

-- Start screensaver after 2.5 minutes

hl.config({
    listener = {
        timeout = 150,
        on-timeout = "pidof hyprlock || omarchy-launch-screensaver",
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

-- Lock system after 5 minutes (screensaver resets idle timer, so have to just do half + 2s margin)

hl.config({
    listener = {
        timeout = 152,
        on-timeout = "omarchy-system-lock",
        on-resume = "omarchy-system-wake",
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output
