-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- source = ~/.config/omarchy/current/theme/hyprlock.conf -> requires manual conversion
-- local hyprlock = require("hyprlock")
-- TODO: convert ~/.config/omarchy/current/theme/hyprlock.conf to .lua and use require()

hl.config({
    general = {
        ignore_empty_input = true,
    },
})

hl.config({
    background = {
        color = color,
        path = "~/.config/omarchy/current/background",
        blur_passes = 3,
    },
})
-- NOTE: Section 'background' may be a plugin or custom section; verify the output

hl.config({
    animations = {
        enabled = false,
    },
})

hl.config({
    input-field = {
        size = { 650, 100 },
        position = { 0, 0 },
        halign = "center",
        valign = "center",
        inner_color = inner_color,
        outer_color = outer_color,
        outline_thickness = 4,
        font_family = "CaskaydiaMono Nerd Font",
        font_color = font_color,
        placeholder_text = "Enter Password",
        check_color = check_color,
        fail_text = "<i>local_var_FAIL (local_var_ATTEMPTS)</i>",
        rounding = 0,
        shadow_passes = 0,
        fade_on_empty = false,
    },
})
-- NOTE: Section 'input-field' may be a plugin or custom section; verify the output

hl.config({
    auth = {
    },
})
-- NOTE: Section 'auth' may be a plugin or custom section; verify the output
