-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Change the default Omarchy look'n'feel

-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.config({
    general = {
        -- No gaps between windows
        gaps_in = 1,
        gaps_out = 6,
        -- Use master layout instead of dwindle
        -- layout = master
        border_size = 2,
        --col.inactive_border = rgba(0,255,38,1) rgba(250,123,5,1) 45deg
        -- col.active_border = rgba(0,34,255,1) rgba(0,255,38,1)
        col = {
            active_border = "rgba(00ff26ff)",
            inactive_border = "rgba(000000ff)",
        },
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#decoration

hl.config({
    decoration = {
        -- Use round window corners
        rounding = 8,
        rounding_power = 4,
        -- opacity or opaque
        --windowrule = opacity 1, match:class ^(com.mitchellh.ghostty)$
        blur = {
            enabled = false,
        },
        shadow = {
            enabled = false,
        },
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#layout

hl.config({
    layout = {
        -- Avoid overly wide single-window layouts on wide screens
        --single_window_aspect_ratio = 1 1
    },
})

hl.config({
    animations = {
        -- enabling all options below will make Hyprland look and feel more fluid, but it may cause performance issues on lower-end hardware. You can enable only the ones you like or need.
        enabled = true,
    },
})

-- bezier curves: name, { x1, y1 }, { x2, y2 } (the two middle control points; p0=(0,0), p3=(1,1))
hl.curve("winOut", { type = "bezier", points = { { 0.20, -0.15 }, { 0, 1 } } })
hl.curve("liner", { type = "bezier", points = { { 1, 1 }, { 1, 1 } } })
hl.curve("md3_standard", { type = "bezier", points = { { 0.12, 0 }, { 0, 1 } } })
hl.curve("overshot", { type = "bezier", points = { { 0.05, 0.85 }, { 0.07, 1.04 } } })
hl.curve("crazyshot", { type = "bezier", points = { { 0.1, 1.22 }, { 0.68, 0.98 } } })
hl.curve("hyprnostretch", { type = "bezier", points = { { 0.05, 0.82 }, { 0.03, 0.94 } } })
hl.curve("easeInOutCirc", { type = "bezier", points = { { 0.75, 0 }, { 0.15, 1 } } })
hl.curve("easeOutCirc", { type = "bezier", points = { { 0, 0.48 }, { 0.38, 1 } } })
hl.curve("easeOutExpo", { type = "bezier", points = { { 0.10, 0.94 }, { 0.23, 0.98 } } })
hl.curve("softAcDecel", { type = "bezier", points = { { 0.20, 0.20 }, { 0.15, 1 } } })
hl.curve("md2", { type = "bezier", points = { { 0.30, 0 }, { 0.15, 1 } } })
hl.curve("OutBack", { type = "bezier", points = { { 0.28, 1.40 }, { 0.58, 1 } } })
hl.curve("md3_decel", { type = "bezier", points = { { 0.05, 0.80 }, { 0.10, 0.97 } } })
hl.curve("menu_decel", { type = "bezier", points = { { 0.05, 0.82 }, { 0, 1 } } })
hl.curve("menu_accel", { type = "bezier", points = { { 0.20, 0 }, { 0.82, 0.10 } } })
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.22, 1 }, { 0.36, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0 }, { 0.35, 1 } } })

-- animations: leaf, enabled, speed, bezier, [style]
hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "windows", enabled = true, speed = 3.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "easeInOutCubic", style = "slidefade 8%" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 3.4, bezier = "easeInOutCubic", style = "slidefade" })
hl.animation({ leaf = "border", enabled = true, speed = 1.6, bezier = "liner" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 100, bezier = "liner", style = "loop" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 2.8, bezier = "easeOutCirc" })
hl.animation({ leaf = "fade", enabled = true, speed = 1.8, bezier = "md3_decel" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 1.8, bezier = "menu_decel", style = "slide" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "menu_accel" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.6, bezier = "menu_decel" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.8, bezier = "menu_accel" })
