name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  flake-checker:
    name: Determinate Systems Flake Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Determinate Systems flake-checker
        uses: DeterminateSystems/flake-checker-action@main

  flake-check:
    name: Nix Flake Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v9

      - name: Run nix flake check
        run: nix flake check
